/**
 * Different types of nodes that are used in our AST.
 */
export type NodeType =
    | 'Program'
    | 'VariableDeclaration'
    | 'VariableDeclarator'
    | 'FunctionDeclaration'
    | 'ClassDeclaration'
    | 'ClassBody'
    | 'MethodDefinition'
    | 'FunctionExpression'
    | 'ExpressionStatement'
    | 'BlockStatement'
    | 'IfStatement'
    | 'ForStatement'
    | 'WhileStatement'
    | 'ReturnStatement'
    | 'BinaryExpression'
    | 'UnaryExpression'
    | 'CallExpression'
    | 'MemberExpression'
    | 'ArrayPattern'
    | 'ObjectPattern'
    | 'AssignmentExpression'
    | 'Identifier'
    | 'Literal'
    | 'ArrayExpression'
    | 'ObjectExpression'
    | 'Property'
    | 'TemplateLiteral'
    | 'TemplateElement'
    | 'ThisExpression'
    | 'NewExpression'
    | 'UpdateExpression'
    | 'LogicalExpression'
    | 'ConditionalExpression'
    | 'AwaitExpression';